### ISSUE TITLE
[Discusión]: Tipos de virtualización

### ISSUE THREAD

**Issue by JJ** [JJ/IV-2015-16#1]
¿Qué tipos de virtualización se deben usar para diferentes aplicaciones de las encontradas en tus prácticas?

**Comment by Makova** [comment]
Suelo utilizar virtualenv para trabajar con Python. Me permite trabajar con distintas versiones de Python, 2.7 a 3.0, a parte de instalar (Distribute)[https://plone-spanish-docs.readthedocs.org/es/latest/python/distribute_pip.html#que-es-distribute] o pip y no tener que romper nada en mi SO, a parte de trabjar sin utilizar sudo=administrador.
Para instalar (virtualnev)[https://plone-spanish-docs.readthedocs.org/es/latest/python/creacion_entornos_virtuales.html]

**Comment by Eudaric** [comment]
Yo usaría virtualización de aplicaciones o virtualización de escritorio si son varias aplicaciones y así poder acceder a ellas desde el navegador.

**Comment by rafaellg8** [comment]
Virtualización de aplicaciones para el uso de algunas prácticas que necesite usar programas específicos de otro sistema operativo, usando wine por ejemplo en un entorno UNIX, y virtualización de entornos de desarrollo para aplicaciones /prácticas en asignturas más orientas a web, en las que tenga que hacer uso de PHP, Python, HTML, etc.

**Comment by romilgildo** [comment]
Para probar distintos sistemas operativos o creación masiva de máquinas virtuales, se debe usar la virtualización plena, ya que con ella se tiene un sistema completo y más eficiente. 

Si se quiere alojar varios clientes en un servidor, de debe optar por la virtualización a nivel de sistema 
operativo  ya  que  esta  nos  permite  aislar  las  cuentas  de  cada  usuario  por  separado.

Para el desarrollo de software elegiría la virtualización de entornos de desarrollo, ya que consigue reproducir cada entorno de producción de la forma más parecida posible y así poder probar nuestro software en él. 

Para el uso de programas específicos de otros sistemas operativos, se puede usar la virtualización de aplicaciones que empaqueta las aplicaciones aislando su entorno de ejecución del resto del sistema operativo.

**Comment by JJ** [comment]
Reabriendo tras cierre accidental.

**Comment by javiergarridomellado** [comment]
Para usar diferentes sistemas operativos o maquinas recurriría a una virtualización completa o plena (VMware,VirtualBox,etc).
En el caso de querer usar un ejecutable .exe o aplicaciones de Windows ( u otro sistema operativo) en un sistema UNIX/Linux usaría una virtualización de aplicaciones como por ejemplo Wine.
En el caso de querer usar las dos versiones de Python recurriría a virtualización de entornos de desarrollo ( este cuatrimestre toca probar este tipo de virtualización )

**Comment by alvaro-gr** [comment]
La virtualización plena la usaría para virtualizar sistemas operativos, si estoy trabajando con el desarrolo de software, según lo que he leido, usuaría la virtualización de aplicaciones, para asilar estas del sistema operativo.

**Comment by neon520** [comment]
Yo utilizaría para prácticas que requieran el uso de varios sistemas operativos diferentes una virtualización completa de cada uno de ellos. Cuando tengo un programa que fue compilado en Windows en unas prácticas previas y necesito usarlo para unas prácticas en Ubuntu utilizo virtualización de aplicaciones.

**Comment by gabriel-stan** [comment]
Para ejecutar otro sistema operativo "invitado" dentro del SSOO "huesped", usaría la virtualización completa con la ayuda de VirtualBox (por ejemplo).
Para los proyectos en python, donde varias aplicaciones requieren diferentes versiones de librerias especificas, he usado la virtualizacion de entorno de desarrollo como "virtualenv", en el cual se puede hacer uso de otra version de python u otra version de Django etc.

**Comment by santidediego** [comment]
Yo he trabajado solamente con dos tipos de virtualizaciones: por un lado he utilizado virtualización completa cuando he tenido que trabajar con máquinas virtuales en Virtualbox (tales como Ubuntu server o Windows Server) y por otro lado también he utilizado Wine como ejemplo de virtualización de aplicaciones para trabajar con aplicaciones de Windows en Linux; esta sobretodo la usé en primero de carrera cuando migré completamente de Windows a Linux y aún necesitaba algunos programas de Windows para mi día a día.

En el caso de tener que trabajar con varias versiones de un programa, como por ejemplo Python, utilizaría virtualización de entorno de desarrollo para no comprometer mi equipo si ocurre algún fallo.

**Comment by sn1k** [comment]
Utilizo la virtualización cuando necesito trabajar en diferentes sistemas operativos o si necesito tocar cosas que ponen en peligro la estabilidad del equipo.  Para todo esto utilizo virtualización completa.
Cuando desde Linux necesito utilizar algunas aplicaciones de windows, utilizo Wine para poder usarlas.

Si estoy desarrollando alguna aplicación que necesita de algún entorno en especial, usaría la virtualización de aplicaciones, para trabajar desde ahí sin comprometer mi equipo.

**Comment by ignaciorecuerda** [comment]
He usado dos tipos de virtualización:
- la virtualización plena la utilizo cuando necesito hacer algo que mi sistema operativo anfitrión no me permite.
- la virtualización de aplicaciones cuando necesito ejecutar alguna aplicación que he creado en un emulador para poder probarla y depurarla.

**Comment by luqueburgosjm** [comment]
Utilizo virtualenvwrapper que es una extensión de virtualenv para python, de éste modo puedo instalar paquetes que sólo voy a usar durante un tiempo y que posteriormente no necesitaré.

**Comment by hugobarzano** [comment]
Si deseará una virtualización plena, para disfrutar de todas las características de un sistema operativo, utilizaría  hipervisores o programas de control. Si quisiera hacer un estudio más detallado de algún recurso concreto, utilizaría la virtualización parcial de dicho recurso. Para conseguir una virtualización a nivel de sistema operativo utilizaría herramientas con las que ya estamos familiarizados como por ejemplo VMware.

**Comment by gabrigm** [comment]
Para trabajar durante poco tiempo con SO's o probarlos para comprobar su funcionamiento yo siempre he preferido la virtualización plena. Así no necesito tener instalado un SO concreto y las ocasiones en que lo necesite puedo virtualizarlo rápidamente con todas sus funciones.

Por otro lado, para la programación web y de aplicaciones considero muy recomendable la vitualización de aplicaciones y de escritorio. Así es mucho más cómodo trabajar desde el lado del servidor y del cliente por separado.

**Comment by jesmorc** [comment]
Uso virtualización plena para crear diferentes máquinas virtuales con diferentes sistemas operativos y diferentes requerimientos de uso, los cuales se ajustan a las diferentes asignaturas de la carrera.

También he usado la misma para crear diferentes tipos de servidores y clientes, todos ellos en máquinas virtuales, y así testear las conexiones entre ellos y conocer la procedencia de los errores que se producen, cuando lo hacen.

La virtualización de aplicaciones la he usado mayormente en emuladores, principalmente de consolas de videojuegos, así como también, por ejemplo, Wine en Linux para usar alguna aplicación de Windows.

**Comment by AngelValera** [comment]
Usaría una virtualización plena si lo que queremos es poder disponer de varias máquinas virtuales con sistemas operativos completos y distintos, para ello podemos usar hipervisores como son VMware Player o VirtualBox, por ejemplo.

Usaría una virtualización de aplicación si lo que queremos es ejecutar una aplicación de Windows en Linux, usando WINE, por ejemplo.

Usaría la virtualización de entornos de desarrollo cuando por ejemplo se quiere usar phyton  y evitar así crear conflictos con el sistema u otros proyectos.

**Comment by Samuc** [comment]
Usaría en un principio una virtualización plena para el caso de necesitar del uso de las características de un SO completo. 

Por ejemplo, para el uso de servidores, en alguna asignatura previa he usado normalmente VirtualBox para virtualizar "Ubuntu Server" o  "Windows Server" .  
También, para emular el sistema Android he usado el emulador BlueStacks.

Por otro lado, en el caso de necesitar del uso de una aplicación específica de otro SO, usaría la virtualización de aplicación, como WINE, para ejecutar software de Windows en otros sistemas operativos.

**Comment by acasadoquijada** [comment]
Únicamente utilizo virtualización plena ya que las aplicaciones que necesito para ciertas asignaturas no funcionan de manera correcta con la virtualización de aplicaciones.

**Comment by cesar2** [comment]
Yo siempre he usado la virtualización plena (ya sea con VMware o VirtualBox) ya que podemos usar los SOs sin modificar. 
En el caso de necesitar ejecutar una aplicación de Windows en otro SO(por ejemplo, Linux) utilizaría virtualización de aplicaciones.

**Comment by nachobit** [comment]
Para el uso de un SO completo, probar su funcionamiento y crear un entorno de trabajo igual al obtenido en una instalación general, lo preferible es la virtualización plena (VirtualBox o en mi caso, Parallels). Para poder ejecutar aplicaciones concretas dentro del SO por problemas de compatibilidades lo mejor es usar herramientas como Wine (virtualización de aplicaciones).

**Comment by mabarrbai** [comment]
Para tener un SO como tal virtualizado, recurriría a la virtualización plena, usando por ejemplo VirtualBox.
Cuando en Linux se quiere ejcutar un ejecutable (.exe) de Windows que no está disponible para Linux, he recurrido a Wine para virtualizar la aplicación concreta.
A nivel de virtualización de sistema operativo, conozco OpenVZ donde anfitrión y clientes usan Linux como sistemas operativos y están totalmente aislados, aunque nunca lo he llegado a utilizar.

**Comment by AntonioPozo** [comment]
Por lo general he usado dos tipos de virtualización:

* Virtualización plena cuando necesito utilizar algún programa de Windows o algún otro de Linux el cual precisa de alguna librería que en OS X no está.
* Virtualización de aplicaciones cuando necesito ejecutar alguna aplicación antigua que se ha quedado sin soporte como Wireshark para OS X

**Comment by bott17** [comment]
Hasta la fecha he utilizado:
* *Virtualización plena*: Para emular sistemas operativos completos por necesidades especificas de la practica en cuestión. Ejemplo claro sería una practica donde requieres montar y configurar un servidor con capacidad de alojar paginas web a la vez que necesito un cliente que pueda abrir dichas paginas webs. Dado que no tengo infraestructura física para poder montar dos ordenadores diferentes necesito virtualizar el cliente o el servidor para poder trabajar con ambos a la vez.
* *Virtualización de aplicaciones*: He utilizado alguna vez Wine en Ubuntu para emular algun programa concreto que necesitaba dentro de ese SO y de forma más directa utilizo Git Bash para emular un terminal bash de linux dentro de windows que ademas me ofrece los comandos de Git.
* *Virtualización de SO*: No he llegado a utilizarlo pero lo veo bastante interesante para disponer de un espacio de trabajo configurado con tareas especificas (ejemplo: Visual studio XXX)  y poder activarlo rapidamente, ademas de poder importarlo a otros espacios de trabajo con rapidez y facilidad

**Comment by bogdananas** [comment]
Para virtualizar un sistema operativo usaría virtualización plena. Programas como VirtualBox lo permite hacer. En algunos casos he utilizado virtualización de aplicaciones  en GNU/Linux para poder ejecutar aplicaciones de Windows.

**Comment by pmmre** [comment]
En el caso de trabajar en mi máquina usararía la virtualización plena ya que con ella puedo compartir elementos e interaccionar entre varias máquinas virtuales de una forma más cómoda aunque pierda algo de rendimiento.

En el caso de tener un servidor compartido con varios clientes  y que no deben de saber de la existencia los unos de los otros usaría una virtualización a nivel de sistema operativo.

Usaría la virtualización parcial si necesito particionar lógicamente un disco duro o alterar la visión virtual de cualquier componente.

La virtualización de desarrollo la usaría para cuando creara nuevo software que necesito comprobar que funciona en diferentes versiones

Y usaría la virtualización de aplicaciones para recrear un entorno de ejecución para programas sin modificar mi sistema actual.

**Comment by javiergama8** [comment]
La virtualización plena la utilizo cuando necesito trabajar con distintos sistemas operativos o en caso de que tenga que realizar tareas que pongan en riesgo mi equipo. Para esta virtualización suelo utilizar VirtualBox.

La virtualización de aplicaciones la he usado principalmente con Wine en Linux para usar alguna aplicación de Windows que he necesitado en un momento dado.

**Comment by srmf9** [comment]
Yo siempre he utilizado  virtualización plena ya sea con VMware Player o VirtualBox ya que me resulta mas cómodo tener preparada varias máquinas virtuales y así no tener que preocuparme de si la  aplicaciones que quiero usar corren o no en mi SO.
Otra ventaja que tiene  la virtualización plena es que es muy sencillo crear tu máquina virtual y borrarla cuando ya no la necesites.

**Comment by JesGor** [comment]
Normalmente en las prácticas en las que he utilizado algún tipo de virtualicación he hecho uso de virtualización plena. Esto se debe a que necesitaba un sistema "independiente" del anfitrión por cualquier razón: en algunos casos necesitaba utilizar un sistema servidor, o un sistema operativo al que modificar demasiados parámetros importantes. Esto me ha permitido no tener que hacer uso de otro dispositivo (ordenador) que contara con estos sistemas, y que no se viera envuelto mi sistema anfitrión en las modificaciones.

En algunas prácticas vamos a utilizar Python, y creo que sería recomendable utilizar la virtualización de entornos de desarrollo. Aunque todavía no he hecho uso de este tipo.

**Comment by crlorenzo7** [comment]
depende, si lo unico que necesito es ejecutar una aplicacion de otro SO, virtualizacion de aplicaciones como cuando tienes que ejecutar una aplicacion de windows en Linux, pero  la mayoria de las veces y para las practicas suelo utilizar la virtualizacion plena, con VMware Player que ademas me resulta mas comoda

**Comment by JA-Gonz** [comment]
-Para varios clientes en un sólo servidor: Usaría una virtualización a nivel de SO, ya que cada usuario comparte el mismo sistema (el servidor), pero todos quedan independientes los unos de los otros, por lo que no hay problemas de seguridad y los cleintes tendrán la sensación final de que tienen un sistema dedicado

-Para crear sistema eficiente web + middleware + bd: Usaría una virtualización total. Primero, tomaría una imagen del sistema operativo y programas exclusivamente necesarios, y haría una imagen de instalación. Esa instalación la pondría en una máquina virtual, ya que así el servidor queda montado rápidamente (y repuesto en caso de pérdidas de datos, ya que tenemos la imagen de instalación). Utilizar una virtualización a nivel de aplicación necesitaría ejecutar "los emuladores" (como WINE), por lo que tenemos corriendo el SO + emulador + aplicación, gastando más recursos.

Para crear un sistema de pruebas software e integración: Yo pondría un sistema de virtualización de entornos de desarrollo, ya que será el que más representa la realidad mientras estamos haciendo los programas / scripts, y tendremos (en teoría) menos problemas a la hora de pasarlo a producción.

**Comment by magvugr** [comment]
Los tipos de virtualización, que voy a encontrar en las prácticas, son de tipo, V. Plena y V. de Aplicaciones.

Cuando necesito utilizar SO sin modificar, utilizamos virtualización plena, en concreto he utilizado VirtualBox, -> https://www.virtualbox.org/. 

Ahora cuando necesito ejecutar una aplicación de un sistema operativo distinto al que tengo, se utiliza una virtualización de aplicaciones, en concreto cuando he necesitado ejecutar un programa de Windows en Linux he utilizado Wine, -> https://www.winehq.org/

**Comment by RosaOR** [comment]
En casi todas las prácticas en las que necesitado virtualización he usado virtualización plena, para tener disponibles todas las funcionalidades del SO que necesito. También en prácticas que se necesita tener más de un sistema operativo funcionando la vez.
Para estos casos utilizo virtualbox.
Otras ocasiones he utilizado virtualización de aplicaciones cuando he necesitado solamente una aplicacion de otro SO.

**Comment by aserranogomez** [comment]
Siempre he usado la virtualización plena, cuando he tenido la necesidad de utilizar varios sistemas operativos o si lo que quiero hacer puede provocar problemas en mi equipo, ya que una vez configurada la máquina, es cómodo ante cualquier error solo tener que restaurar la copia de seguridad. En casi todas las ocasiones que lo he necesitado he usado virtualbox salvo algunas ocasiones que he usado vmware.

**Comment by manolotello7** [comment]
La virtualización plena la utilizo cuando necesito trabajar con distintos sistemas operativos, o cuando tenga que realizar tareas que pongan en riesgo mi equipo. Suelo utilizar VirtualBox o VMware.

Para usar alguna aplicación de Windows que he necesitado en un momento dado, he usado la virtualización de aplicaciones principalmente en linux con Wine.

**Comment by azpe** [comment]
Suelo hacer uso de Virtualización plena para virtualizar SOs como Ubuntu Server, Centos, Windows Server o Red Hat sobre un SO anfitrion Windows mediante VMware Player o VirtualBox.

Tambíen he usado virtualización de aplicaciones al usar CygWin para usar RRDTool y poder desplegar Cacti.

**Comment by araluce** [comment]
Usaría una virtualización de entornos de desarrollo para probar versiones diferentes de las mismas aplicaciones.

Virtualización plena para virtualizar diferentes sistemas operativos y un virtualizador de aplicaciones como Wine para correr ejecutables no soportados en el sistema operativo actual.

**Comment by reyic** [comment]
Para las diferentes aplicaciones encontradas en mis practicas utilizaria:
Virtualizacion plena para utilizar sistemas operativos como ubuntu-server.
Virtualizacion de entornos de desarrollo para la realizacion de aplicaciones.

**Comment by adalsa91** [comment]
Si necesito ejecutar varias aplicaciones y funcionalidades de un SO de forma simultanea utilizo virtualización plena mediante el uso de hipervisores, normalmente de tipo 2 como VirtualBox. En caso de necesitar ejecutar solo una apliación específica sin necesidad explícita de las demás funciones del SO usaría virtualización de aplicaciones usando algún emulador como Wine. Cuando se necesita probar aplicaciones en un entorno seguro y que simule al de producción es recomendable usar contenedores (virtualización a nivel de sistema operativo) como por ejemplo Docker.

**Comment by 0rfeo** [comment]
Siempre he usado virtualización plena en todas mis prácticas, para tener la funcionalidad del Sistema Operativo y para que realizar tareas que no pongan en peligro el equipo
Siempre he usado VMware para ello.

**Comment by koji3** [comment]
Se suele utilizar virtualizacion plena para ejecutar sistemas operativos enteros y utilizar funciones que no soporta el sistema anfitrión, asi como para instalar servidores privados virtuales (VPS). 
He utilizado virtualización de aplicaciones cuando he usado algún servicio de escritorio virtual, por ejemplo

**Comment by aravergar** [comment]
Suelo usar virtualización plena para operar con diferentes Ubuntu Server. También para virtualizar Windows en una máquina Ubuntu o Ubuntu en Windows ocasionalmente. También he tenido que usar virtualización de aplicaciones, con Wine, para emular aplicaciones de Windows en un entorno Linux. Con todo, mi mayor uso ha sido la virtualización plena de servidores.
