### ISSUE TITLE
Nombre de los ficheros de objectivos y ejercicios.

### ISSUE THREAD

**Issue by FranciscoNaveros** [JJ/IV-2015-16#12]
Cuando subais los ficheros con los objetivos o los ejercicios, poned vuestro nombre en el nombre del fichero para que sea más facil identificaros.

**Comment by Makova** [comment]
Yo en el Tema1 lo he puesto en el título, creo que se visualiza mejor que dentro del archivo.

**Comment by Makova** [comment]
Al final queda mejor en carpetas con nuestros nombres y apellidos y dentro los ejercicios de los temas.

**Comment by FranciscoNaveros** [comment]
Por favor, revisad vuestro ficheros de objetivos, carpeta de ejercicios y enlace en el fichero de prácticas y poned en todos vuestro nombre completo (EL MISMO EN TODOS LOS FICHEROS). No me pongais en uno el nombre y el primer apellido, en otro el nombre y el segundo apellido y en otro el segundo nombre y el segundo apellido (que se han dado casos)
