### ISSUE TITLE
Error con zsh y docker

### ISSUE THREAD

**Issue by Makova** [JJ/IV-2015-16#22]
Estoy intentando utilizar Docker con ZSH.
 
Me tira un error al bajar ubuntu con docker, en vez de bash utilizo zsh:

**sudo docker -it ubuntu zsh**     *en vez de*         **sudo docker -it ubuntu bash**

* El error:   
**exec: "zsh": executable file not found in $PATH**

Pero si lo tengo añadido.

**export ZSH=$HOME/ .oh-my-zsh**

**Comment by luqueburgosjm** [comment]
En mi SO (arch) oh-my-zsh está en /usr/share/oh-my-zsh y no en $HOME/ .oh-my-zsh.

No sé si esto te servirá de ayuda.

**Comment by Makova** [comment]
Hola @luqueburgosjm 
Pues puede ser, en **/usr/share/** solo tengo la carpeta **zsh**, aunque cuando la cambie por bash creo que ya lo hicé. Aún así por probar no pierdo nada. 
¡¡Gracias!!

**Comment by Makova** [comment]
Esta:

`[~]$ echo $SHELL`
`/usr/bin/zsh`

Seguiré desde aquí [ZSH Wiki](https://wiki.archlinux.org/index.php/Zsh_%28Espa%C3%B1ol%29)

**Comment by JJ** [comment]
Manu, el contenedor es una "máquina virtual" diferente. Tienes que instalar
zsh en el mismo si quieres que funciona.
