### ISSUE TITLE
¿Pull requests desde CLI en Linux?

### ISSUE THREAD

**Issue by adalsa91** [JJ/IV-2015-16#323]
¿Existe alguna forma de hacer pull requests desde línea de comandos en Linux?

**Comment by bott17** [comment]
Existe una forma de crear pull request a nivel de git: http://git-scm.com/docs/git-request-pull  no obstante creo que esto no genera un pull request en github.
Buscando encontre un proyecto para añadir la funcionalidad, aunque no he podido probarlo: https://github.com/svs/pull
También he visto a gente utilizando scripts para automatizarlo: http://www.devthought.com/code/create-a-github-pull-request-from-the-terminal/

**Comment by JJ** [comment]
Tienes que usar "hub", el cliente de GitHub. Es una funcionalidad de la web
y por eso necesita una app cliente.
