### ISSUE TITLE
Formato ilegible Tema 3 

### ISSUE THREAD

**Issue by romilgildo** [JJ/IV-2015-16#400]
¿Podria algún profesor arreglar el tema 3? Es que a partir del ejercicio 4 no se puede leer bien.
Enlace: [http://jj.github.io/IV/documentos/temas/PaaS](http://jj.github.io/IV/documentos/temas/PaaS)

Gracias

**Comment by JJ** [comment]
Totalmente cierto. Gracias por avisar.
