### ISSUE TITLE
Error en la guía del tema del hito 4

### ISSUE THREAD

**Issue by santidediego** [JJ/IV-2015-16#825]
En el ejercicio 9, donde pone que hay que usar la imagen que nos devuelve `docker images -notrunc` no funciona. Ese no es el id que  hay que utilizar. En su lugar, a mi me ha funcionado entrando dentro del contenedor con `docker run -t -i ubuntu /bin/bash` y copiando el número que aparece junto al usuario root en el prompt. Ese es el ID que hay que utilizar, sino probablemente dará error de que no encuentra el ID.

**Comment by JJ** [comment]
Gracias, Santiago.

**Comment by JJ** [comment]
Creo que ese ejemplo se ha eliminado ya.
