### ISSUE TITLE
¿Cómo se calcula el precio de un producto sin IVA?

### ISSUE THREAD

**Issue by FranciscoNaveros** [JJ/IV-2015-16#92]
Revisando los ejercicios de varios alumnos he visto varios fallos a la hora de calcular el precio de un producto sin IVA partiendo de uno con IVA.

¿Cual es la fórmula correcta para calcularlo?

**Comment by romilgildo** [comment]
Creo que se hace con la siguiente fórmula:

Precio con IVA / 1.(porcentaje de IVA)

Por ejemplo, si el precio con IVA es de 1000 €, y el porcentaje de IVA que se le aplica al producto es del 21%, deberíamos hacer 1000 / 1.21 = 826,45 €

**Comment by magvugr** [comment]
La respuesta del compañero Romildildo, está perfecta, yo presento otra forma, para calcular el precio es: 

(Precio Producto Con Iva) * 0,21 (En el caso de ser 21% de Iva) = (Resultado Iva del Producto).

(Precio Producto con Iva) - (Resultado Iva del Producto) = Precio Producto sin Iva
